### ISSUE TITLE
Routes folder missing in this prepack

### ISSUE THREAD

**Issue by lohithram** [ipselon/bootstrap-prepack#1]
Hi,

Just dowloaded and tried to build the client and found the below error.
ERROR in ./src/client/main.js
    Module not found: Error: Cannot resolve 'file' or 'directory' ./routes/routes.js in /Users/lohithram/Workspace/bootstrap-prepack/src/client
     @ ./src/client/main.js 23:22-51

**Comment by ipselon** [comment]
You need to export project in Structor first and routes will appear.

**Comment by ipselon** [comment]
Fixed missing routes folder. @lohithram thanks!

**Comment by lohithram** [comment]
Coo.. Cheers!
