### ISSUE TITLE
There has a problem

### ISSUE THREAD

**Issue by wibin86** [ipselon/bootstrap-prepack#3]
When i go to http://localhost:3000 or http://localhost:3000/server,show nothing,and the chrome develop tools show error: “”Cannot find module "!!./../../../../node_modules/css-loader/index.js!./react-widgets.css"

**Comment by ipselon** [comment]
@wibin86 could you provide steps you were doing before starting the server? I need to understand that you are doing all by the instruction which is in Readme.
