### ISSUE TITLE
The metadata is likely doesn't work 

### ISSUE THREAD

**Issue by xhbisme** [ipselon/bootstrap-prepack#6]
how to use the metadata to control my code?
I tried to click the new component button and run a generator,input the metadata , but it is vain.it always create the same code.must I write a generator by hand?

**Comment by ipselon** [comment]
@xhbisme What component generator you were using to generate new component?

**Comment by xhbisme** [comment]
Generics/Views/SimpleModelComponent,Generics/Controllers/NoSagas/Component...and so on,It seemed I use the metadata in a wrong way and it always create the same code. need I buy some service?

**Comment by xhbisme** [comment]
Most important,where should I write my own metadata? After I clicked run generator,there is a place can write metadata,is there?

**Comment by xhbisme** [comment]
@ipselon Thanks for your help .
